name: pangy
channels:
  - conda-forge/label/metpy_rc
  - conda-forge
  - defaults
dependencies:
  - jupyterlab>=1.2
  - matplotlib
  - ipympl
  - nodejs
  - pandas
  - geopandas
  - tqdm
  - dask
  - metpy
  - siphon
  - xarray
  - netcdf4
  
